CREATE TABLE IF NOT EXISTS "ai_model" (
  "id" uuid DEFAULT pg_catalog.gen_random_uuid() PRIMARY KEY,
  "provider" text NOT NULL,
  "name" text NOT NULL,
  "created_at" timestamp DEFAULT now() NOT NULL,
  "updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "ai_model_provider_name_idx" ON "ai_model" ("provider", "name");
CREATE INDEX IF NOT EXISTS "ai_model_provider_idx" ON "ai_model" ("provider");

-- Seed initial catalog (mirrors public/models.json). Re-running is safe.
INSERT INTO "ai_model" ("provider", "name") VALUES
  ('anthropic', 'claude-3-5-haiku-20241022'),
  ('anthropic', 'claude-3-5-haiku-latest'),
  ('anthropic', 'claude-3-5-sonnet-20240620'),
  ('anthropic', 'claude-3-5-sonnet-20241022'),
  ('anthropic', 'claude-3-7-sonnet-20250219'),
  ('anthropic', 'claude-3-haiku-20240307'),
  ('anthropic', 'claude-3-opus-20240229'),
  ('anthropic', 'claude-3-sonnet-20240229'),
  ('anthropic', 'claude-haiku-4-5'),
  ('anthropic', 'claude-haiku-4-5-20251001'),
  ('anthropic', 'claude-opus-4-0'),
  ('anthropic', 'claude-opus-4-1'),
  ('anthropic', 'claude-opus-4-1-20250805'),
  ('anthropic', 'claude-opus-4-20250514'),
  ('anthropic', 'claude-opus-4-5'),
  ('anthropic', 'claude-opus-4-5-20251101'),
  ('anthropic', 'claude-opus-4-6'),
  ('anthropic', 'claude-sonnet-4-0'),
  ('anthropic', 'claude-sonnet-4-20250514'),
  ('anthropic', 'claude-sonnet-4-5'),
  ('anthropic', 'claude-sonnet-4-5-20250929'),
  ('anthropic', 'claude-sonnet-4-6'),
  ('google', 'gemini-1.5-flash'),
  ('google', 'gemini-1.5-flash-8b'),
  ('google', 'gemini-1.5-pro'),
  ('google', 'gemini-2.0-flash'),
  ('google', 'gemini-2.0-flash-lite'),
  ('google', 'gemini-2.5-flash'),
  ('google', 'gemini-2.5-flash-lite'),
  ('google', 'gemini-2.5-flash-lite-preview-06-17'),
  ('google', 'gemini-2.5-flash-preview-04-17'),
  ('google', 'gemini-2.5-flash-preview-05-20'),
  ('google', 'gemini-2.5-flash-preview-09-2025'),
  ('google', 'gemini-2.5-pro'),
  ('google', 'gemini-2.5-pro-preview-05-06'),
  ('google', 'gemini-2.5-pro-preview-06-05'),
  ('google', 'gemini-3-flash-preview'),
  ('google', 'gemini-3-pro-preview'),
  ('google', 'gemini-3.1-flash-lite-preview'),
  ('google', 'gemini-3.1-pro-preview'),
  ('google', 'gemini-3.1-pro-preview-customtools'),
  ('google', 'gemini-flash-latest'),
  ('google', 'gemini-flash-lite-latest'),
  ('google', 'gemini-live-2.5-flash'),
  ('google', 'gemma-3-27b-it'),
  ('google', 'gemma-4-26b'),
  ('google', 'gemma-4-31b'),
  ('openai', 'codex-mini-latest'),
  ('openai', 'gpt-4'),
  ('openai', 'gpt-4-turbo'),
  ('openai', 'gpt-4.1'),
  ('openai', 'gpt-4.1-mini'),
  ('openai', 'gpt-4.1-nano'),
  ('openai', 'gpt-4o'),
  ('openai', 'gpt-4o-mini'),
  ('openai', 'gpt-5'),
  ('openai', 'gpt-5-mini'),
  ('openai', 'gpt-5-nano'),
  ('openai', 'o1'),
  ('openai', 'o3'),
  ('openai', 'o3-mini'),
  ('openai', 'o4-mini'),
  ('openrouter', 'anthropic/claude-sonnet-4-6'),
  ('openrouter', 'anthropic/claude-opus-4-6'),
  ('openrouter', 'anthropic/claude-haiku-4-5-20251001'),
  ('openrouter', 'google/gemini-2.5-pro'),
  ('openrouter', 'google/gemini-2.5-flash'),
  ('openrouter', 'google/gemini-2.0-flash'),
  ('openrouter', 'google/gemini-2.0-flash-exp:free'),
  ('openrouter', 'mistralai/mistral-large-latest'),
  ('openrouter', 'mistralai/mistral-medium-latest'),
  ('openrouter', 'mistralai/mistral-small-latest'),
  ('openrouter', 'mistralai/codestral-latest'),
  ('openrouter', 'mistralai/devstral-medium-latest'),
  ('openrouter', 'meta-llama/llama-3.3-70b-instruct'),
  ('openrouter', 'meta-llama/llama-3.1-8b-instruct'),
  ('openrouter', 'meta-llama/llama-3.3-70b-instruct:free'),
  ('openrouter', 'nvidia/nemotron-3-super-120b-a12b:free'),
  ('openrouter', 'qwen/qwen3-32b'),
  ('openrouter', 'qwen/qwen3-235b-a22b'),
  ('openrouter', 'qwen/qwen3.6-plus'),
  ('openrouter', 'deepseek/deepseek-chat-v3-0324'),
  ('openrouter', 'deepseek/deepseek-r1'),
  ('openrouter', 'x-ai/grok-4'),
  ('openrouter', 'x-ai/grok-3'),
  ('openrouter', 'x-ai/grok-3-mini'),
  ('openrouter', 'cohere/command-r-plus'),
  ('openrouter', 'cohere/command-r'),
  ('openrouter', 'perplexity/sonar-pro'),
  ('openrouter', 'perplexity/sonar-reasoning'),
  ('openrouter', 'groq/llama-3.3-70b-versatile'),
  ('openrouter', 'groq/compound-beta'),
  ('openrouter', 'groq/compound-beta-mini')
ON CONFLICT ("provider", "name") DO NOTHING;
