import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

/**
 * Detect if a user message is requesting a document/file generation.
 */
export function detectDocumentRequest(userMessage: string): "pdf" | null {
  const lower = userMessage.toLowerCase();

  const keywords = [
    "create a document", "create a report", "create a file",
    "generate a document", "generate a report", "generate a file",
    "make a document", "make a report", "make a file",
    "give me a document", "give me a report", "give me a file",
    "write a document", "write a report",
    "send me a document", "send me a report", "send me a file",
    "as a pdf", "as pdf", "in pdf", "pdf file", "pdf document", "pdf report",
    "as a file", "as a document",
    "export as", "download as",
    "prepare a report", "prepare a document",
  ];

  for (const kw of keywords) {
    if (lower.includes(kw)) return "pdf";
  }
  return null;
}

/**
 * Extract a suitable filename from the user message.
 */
export function extractFilename(userMessage: string, agentType: string): string {
  const lower = userMessage.toLowerCase();
  const subjects = [
    "report", "analysis", "forecast", "budget", "statement",
    "summary", "overview", "plan", "strategy", "review",
  ];
  for (const s of subjects) {
    if (lower.includes(s)) return `${agentType}-${s}`;
  }
  return `${agentType}-document`;
}

/**
 * Generate a PDF buffer from text content using pdf-lib (no native dependencies).
 */
export async function generatePdf(
  content: string,
  title: string,
  agentType: string,
): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  doc.setTitle(title);
  doc.setAuthor(`${agentType.charAt(0).toUpperCase() + agentType.slice(1)} Agent`);
  doc.setCreator("OpenClaw Agent Platform");

  const headerColor = agentType === "finance"
    ? rgb(0.18, 0.49, 0.20)
    : agentType === "marketing"
      ? rgb(0.08, 0.40, 0.75)
      : rgb(0.90, 0.32, 0.00);

  const PAGE_W = 595.28; // A4
  const PAGE_H = 841.89;
  const MARGIN = 60;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  const LINE_HEIGHT = 16;
  const FONT_SIZE = 11;
  const HEADING_SIZES = { h1: 20, h2: 16, h3: 13 };

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;

  // Header bar
  page.drawRectangle({ x: 0, y: PAGE_H - 8, width: PAGE_W, height: 8, color: headerColor });
  y -= 10;

  // Title
  const titleWidth = fontBold.widthOfTextAtSize(title, 22);
  page.drawText(title, {
    x: (PAGE_W - titleWidth) / 2,
    y,
    size: 22,
    font: fontBold,
    color: rgb(0.1, 0.1, 0.1),
  });
  y -= 24;

  // Subtitle
  const subtitle = `${agentType.charAt(0).toUpperCase() + agentType.slice(1)} Agent  •  ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`;
  const subWidth = font.widthOfTextAtSize(subtitle, 10);
  page.drawText(subtitle, {
    x: (PAGE_W - subWidth) / 2,
    y,
    size: 10,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });
  y -= 20;

  // Divider
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_W - MARGIN, y },
    thickness: 0.5,
    color: rgb(0.8, 0.8, 0.8),
  });
  y -= 20;

  // Helper to add a new page if needed
  function ensureSpace(needed: number) {
    if (y - needed < MARGIN + 30) {
      // Footer on current page
      addFooter(page, doc.getPageCount());
      page = doc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - MARGIN;
    }
  }

  function addFooter(p: typeof page, pageNum: number) {
    const footerText = `Generated by OpenClaw ${agentType.charAt(0).toUpperCase() + agentType.slice(1)} Agent  •  Page ${pageNum}`;
    const fw = font.widthOfTextAtSize(footerText, 8);
    p.drawText(footerText, {
      x: (PAGE_W - fw) / 2,
      y: 30,
      size: 8,
      font,
      color: rgb(0.6, 0.6, 0.6),
    });
  }

  // Word-wrap helper
  function wrapText(text: string, f: typeof font, size: number, maxWidth: number): string[] {
    const words = text.split(" ");
    const lines: string[] = [];
    let current = "";
    for (const word of words) {
      const test = current ? `${current} ${word}` : word;
      if (f.widthOfTextAtSize(test, size) > maxWidth) {
        if (current) lines.push(current);
        current = word;
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
    return lines.length ? lines : [""];
  }

  // Parse and render content
  const lines = content.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();

    if (!trimmed) {
      y -= LINE_HEIGHT * 0.5;
      continue;
    }

    // Strip markdown bold markers for display
    const clean = trimmed.replace(/\*\*/g, "");

    if (trimmed.startsWith("### ")) {
      ensureSpace(HEADING_SIZES.h3 + 10);
      y -= 6;
      const heading = clean.replace(/^###\s*/, "");
      page.drawText(heading, { x: MARGIN, y, size: HEADING_SIZES.h3, font: fontBold, color: rgb(0.2, 0.2, 0.2) });
      y -= HEADING_SIZES.h3 + 4;
    } else if (trimmed.startsWith("## ")) {
      ensureSpace(HEADING_SIZES.h2 + 10);
      y -= 8;
      const heading = clean.replace(/^##\s*/, "");
      page.drawText(heading, { x: MARGIN, y, size: HEADING_SIZES.h2, font: fontBold, color: rgb(0.13, 0.13, 0.13) });
      y -= HEADING_SIZES.h2 + 4;
    } else if (trimmed.startsWith("# ")) {
      ensureSpace(HEADING_SIZES.h1 + 10);
      y -= 10;
      const heading = clean.replace(/^#\s*/, "");
      page.drawText(heading, { x: MARGIN, y, size: HEADING_SIZES.h1, font: fontBold, color: rgb(0.1, 0.1, 0.1) });
      y -= HEADING_SIZES.h1 + 4;
    } else if (trimmed.startsWith("---")) {
      y -= 6;
      page.drawLine({
        start: { x: MARGIN, y },
        end: { x: PAGE_W - MARGIN, y },
        thickness: 0.5,
        color: rgb(0.85, 0.85, 0.85),
      });
      y -= 10;
    } else if (trimmed.startsWith("* ") || trimmed.startsWith("- ")) {
      const bulletText = clean.replace(/^[*-]\s+/, "");
      const wrapped = wrapText(bulletText, font, FONT_SIZE, CONTENT_W - 20);
      for (let i = 0; i < wrapped.length; i++) {
        ensureSpace(LINE_HEIGHT);
        if (i === 0) {
          page.drawText("•", { x: MARGIN + 4, y, size: FONT_SIZE, font, color: rgb(0.2, 0.2, 0.2) });
        }
        page.drawText(wrapped[i], { x: MARGIN + 18, y, size: FONT_SIZE, font, color: rgb(0.2, 0.2, 0.2) });
        y -= LINE_HEIGHT;
      }
    } else {
      // Regular text — check if it's bold
      const isBold = trimmed.startsWith("**") && trimmed.endsWith("**");
      const textFont = isBold ? fontBold : font;
      const wrapped = wrapText(clean, textFont, FONT_SIZE, CONTENT_W);
      for (const wl of wrapped) {
        ensureSpace(LINE_HEIGHT);
        page.drawText(wl, { x: MARGIN, y, size: FONT_SIZE, font: textFont, color: rgb(0.2, 0.2, 0.2) });
        y -= LINE_HEIGHT;
      }
    }
  }

  // Footer on last page
  addFooter(page, doc.getPageCount());

  const pdfBytes = await doc.save();
  return Buffer.from(pdfBytes);
}
